config/routes.rb
Rails.application.routes.draw do
  get 'items/new'

  get 'sessions/new'
  get '/signup', to: 'survivals#new'
  get '/profile', to: 'survivals#show'

  root 'app_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/survivals/mark_infected', to: 'survivals#mark_infected'
  get '/report', to: 'survivals#report'

  resources :survivals
  resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :survival
    validates :fiji_water, presence: true,numericality: { greater_than_or_equal_to: 0}
    validates :campbell_soup, presence: true,numericality: { greater_than_or_equal_to: 0}
    validates :first_aid_pouch, presence: true,numericality: { greater_than_or_equal_to: 0}
    validates :ak, presence: true,numericality: { greater_than_or_equal_to: 0}
end

app/models/survival.rb
class Survival < ApplicationRecord
    has_many :items
    has_one_attached :avatar

    before_save { email.downcase }
    validates :name, presence: true, length: { minimum: 3, maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    validates :age, presence: true
    validates :gender, presence: true

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
end

app/controllers/app_pages_controller.rb
class AppPagesController < ApplicationController
  def home
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(items_params)
    @item.survival_id = current_user.id
    if @item.save
      flash[:success] = "Welcome to Zombie Apocalypse"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    if logged_in?
      @find_user = params[:id]
      @item = Item.find_by(survival_id: @find_user)
      if !@item
        flash[:danger] = "Sorry, No items found"
        redirect_to survivals_path
      end
    else
      flash[:warning] = "Please sign up first!"
      redirect_to root_path
    end
  end

  def edit
    redirect_to root_path
  end

  def index
    redirect_to root_path
  end

  def items_params
    params.require(:item).permit(:fiji_water,:campbell_soup,:first_aid_pouch,:ak)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    survival = Survival.find_by(email: params[:session][:email].downcase)
    if survival && survival.authenticate(params[:session][:password])
      log_in survival
      redirect_to survival
    else
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/survivals_controller.rb
class SurvivalsController < ApplicationController

  def show
    if logged_in?
      if correct_user
        @survival = Survival.find(params[:id])
      end
    else
      redirect_to root_path
    end
  end
  def new
    if !logged_in?
      @survival = Survival.new
    else
      redirect_to root_path
    end
  end

  def create
    @survival = Survival.new(survival_params)

    if @survival.save
      log_in @survival
      redirect_to items_new_path
    else
      render 'new'
    end
  end

  def edit
    @survival = Survival.find(params[:id])
    if logged_in? && current_user.id == @survival.id
      @survival = Survival.find(params[:id])
    else
      flash[:warning] = "You are not allowed to update this survival!"
      redirect_to root_path
    end
  end

  def update
    @survival = Survival.find(params[:id])

    if logged_in? && current_user.id == @survival.id
      if @survival.update(update_params)
        flash[:success] = "Profile Updated"
        redirect_to @survival
      else
        render 'edit'
      end
    else
      redirect_to root_path
    end
  end

  def index
    if logged_in?
      @survivals = Survival.all
    else
      flash[:warning] = "Please Login to see survivals"
      redirect_to root_path
    end
  end

  def mark_infected
    @current_survival_id = params[:id]
    @survival = Survival.find_by(id: @current_survival_id)

    @survival.marked_infected_by = current_user.id
    @success = false

    if @survival.update_attribute(:isInfectedCount, @infected_count)
      @success = true
    end

    render json: {data: @success}
  end

  def report
    if logged_in?
      @survivors = Survival.all

      @infected_count = 0
      @non_infected_count = 0
      @infected_percentage
      @non_infected_percentage

      @survivors.each do |s|
        if s.isInfectedCount && s.isInfectedCount >=5
          @infected_count = @infected_count + 1
        else
          @non_infected_count = @non_infected_count + 1
        end
      end
    else
      flash[:warning] = "Please Login to see report"
      redirect_to root_path
    end
  end




  def survival_params
    params.require(:survival).permit(:avatar,:name,:email,:age,:gender,:password,:password_confirmation)
  end

  def update_params
      params.require(:survival).permit(:avatar)
  end
end

app/helpers/app_pages_helper.rb
module AppPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(survival)
        session[:survival_id] = survival.id
    end
    def current_user
        if session[:survival_id]
            @current_user ||= Survival.find_by(id: session[:survival_id])
        end
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        session.delete(:survival_id)
        @current_user = nil
    end
    def current_user?(survival)
        survival && survival == current_user
    end
    def correct_user
        @survival = Survival.find(params[:id])
        redirect_to(root_url) unless @survival == current_user
    end
end

app/helpers/survivals_helper.rb
module SurvivalsHelper
end

app/views/app_pages/home.html.erb
<% provide(:title, "Home") %>
<!Doctype html>
<html>
<head>
    <title><%= yield(:title) %></title>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-md-offset-3 jumbotron">
                <div>
                    <% if logged_in? %>
                        <h3>Hi <%= current_user.name %>
                    <% end %>
                    <h4>Welcome to Zombie Apocalypse</h4>
                    <p>Its the Zombie Apocalypse Survival App</p>
                    <div>
                        <% if !logged_in? %>
                            <%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-primary btn_signup" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/views/items/new.html.erb
<% provide(:title, "Items") %>
<!Doctype html>
<html>
    <head><title><%= yield(:title) %></title></head>
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 col-md-offset-3">
                    <h2 class="text-center">Declare Items</h2>
                    <%= form_with(model: @item, local: true) do |f| %>
                        <%= render 'shared/items_error_messages' %>
                        <%= f.label "Fiji Water" %>
                        <%= f.number_field :fiji_water, class: "form-control mb-2"%>

                        <%= f.label "Campbell Soup" %>
                        <%= f.number_field :campbell_soup, class: "form-control mb-2"%>

                        <%= f.label "First Aid Pouch" %>
                        <%= f.number_field :first_aid_pouch, class: "form-control mb-2" %>

                        <%= f.label "AK47" %>
                        <%= f.number_field :ak, class: "form-control mb-2" %>

                        <%= f.submit "Save Items", class: "btn btn-primary form-control mt-3" %>
                    <% end %>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/items/show.html.erb
<% provide(:title, "My Items") %>
<!Doctype html>
<html>
    <head><title><%= yield(:title) %></title></head>
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-sm-12 col-xs-12 table-responsive col-md-offset-3">
                    <h2 class="text-center">My Items</h2>
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <td class="table-dark">Fiji Water</td>
                            <td><%= @item.fiji_water %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">Campbell Soup</td>
                            <td><%= @item.campbell_soup %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">First Aid Pouch</td>
                            <td><%= @item.first_aid_pouch %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">AK47</td>
                            <td><%= @item.ak %></td>
                        </tr>
                        <tr>
                            <td colspan="2"><%= link_to "Go to survivals", survivals_path, class: "btn btn-secondary" %></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/layouts/_header.html.erb
<header class="mb-5">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
        <%= link_to 'Zombie Apocalypse', root_path, class: "navbar-brand navbar-brand-heading" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mr-5">
                    <%= link_to 'Home', root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <% if logged_in? %>
                    <li><%= link_to 'Report', report_path, class: "nav-link pr-5" %></li>
                    <li><%= link_to 'Survivals', survivals_path, class: "nav-link pr-5 mt-" %></li>
                    <li class="nav-item dropdown pr-5">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            <% if current_user.avatar.attached? %>
                                <image src="<%= (url_for(current_user.avatar)) %>" class="survival-avatar header-avatar">
                            <% end %>
                            <%= current_user.name %>
                        </a>
                    <div class="dropdown-menu">
                        <%= link_to 'My Profile', survival_path(current_user.id), class: 'dropdown-item' %>
                        <% if !(current_user.isInfectedCount && current_user.isInfectedCount >=5) %>
                        <%= link_to 'My Items', item_path(current_user.id), class: 'dropdown-item' %>
                        <% end %>
                        <%= link_to 'Update Profile', edit_survival_path(current_user.id), class: 'dropdown-item' %>
                        <%= link_to 'Logout', logout_path, method: :delete, class: "dropdown-item" %>
                    </div>
                </li>
                    <% else %>
                    <%= link_to 'Login', login_path, class: "nav-link" %>
                    <% end %>
                </li>
            </ul>
        </div>
    </nav>
    <br>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zombie Apocalypse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application'%>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%=
      message %></div>
    <% end %>
    </div>
    </div>
  </div>
  <%= yield %>

  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @survival.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
        The form contains <%= pluralize(@survival.errors.count,
        "error") %>.
        </div>
        <ul>
            <% @survival.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_items_error_messages.html.erb
<% if @item.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
        The form contains <%= pluralize(@item.errors.count,
        "error") %>.
        </div>
        <ul>
            <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/survivals/edit.html.erb
<% provide(:title, "Update Profile") %>
<!Doctype html>
<html>
    <head><title><%= yield(:title) %></title></head>
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 col-md-offset-3">
                    <h2 class="text-center">Update Profile</h2>
                    <%= form_with(model: @survival, local: true) do |f| %>
                        <%= f.label "Change Picture" %>
                        <%= f.file_field :avatar, class: "form-control mb-2"%>

                        <%= f.submit "Update Profile", class: "btn btn-warning form-control mt-3" %>
                        <%= link_to "Back", survival_path(current_user.id), class: "btn btn-secondary form-control mt-3" %>
                    <% end %>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/survivals/index.html.erb
<% provide(:title, "All Survivals") %>
<!Doctype html>
<html>
    <head><title><%= yield(:title) %></title></head>
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-sm-12 col-xs-12 table-responsive col-md-offset-3">
                    <h2 class="text-center">All Survivals</h2>
                    <% @survivals.each do |survival| %>
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <td class="table-dark">Profile Picture</td>
                            <td>
                                <% if survival.avatar.attached? %>
                                    <div><image src="<%= (url_for(survival.avatar)) %>" class="survival-avatar"></div>
                                <% else %>
                                    <p>No image found</p>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <td class="table-dark">Name</td>
                            <td><%= survival.name %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">Age</td>
                            <td><%= survival.age %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">Gender</td>
                            <td><%= survival.gender %></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <% if !(current_user.isInfectedCount && current_user.isInfectedCount >=5) %>
                                    <%= link_to "Show Items", item_path(survival.id), class:"btn btn-secondary btn-sm" %>
                                    <% if current_user.id != survival.id %>
                                        <% if survival.marked_infected_by == current_user.id %>
                                            <button disabled class="btn btn-warning btn-sm">Already Marked Infected!</button>
                                        <% else %>
                                            <button class="btn btn-warning btn-sm" id="btn_contaminated" current_id=<%= survival.id %>>Mark Infected</button>
                                        <% end %>
                                    <% end %>
                                <% end %>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <% end %>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/survivals/new.html.erb
<% provide(:title, "Sign Up") %>
<!Doctype html>
<html>
    <head><title><%= yield(:title) %></title></head>
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 col-md-offset-3">
                    <h2 class="text-center">Sign Up</h2>
                    <%= form_with(model: @survival, local: true) do |f| %>
                        <%= render 'shared/error_messages' %>
                        <%= f.label "Profile Picture" %>
                        <%= f.file_field :avatar, class: "form-control mb-2"%>

                        <%= f.label :name %>
                        <%= f.text_field :name, class: "form-control mb-2"%>

                        <%= f.label :email %>
                        <%= f.text_field :email, class: "form-control mb-2" %>

                        <%= f.label :age %>
                        <%= f.number_field :age, class: "form-control mb-2" %>

                        <%= f.label :gender %>
                        <%= f.select(:gender, options_for_select([['Male'], ['Female'], ['Other']]), {}, {class: "form-control mb-2"}) %>

                        <%= f.label :password %>
                        <%= f.password_field :password, class: "form-control mb-2" %>

                        <%= f.label :password_confirmation, "Confirmation" %>
                        <%= f.password_field :password_confirmation, class: "form-control mb-2" %>

                        <%= f.submit "Create Account", class: "btn btn-primary form-control mt-3" %>
                    <% end %>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/survivals/report.html.erb
<% provide(:title, "Report") %>
<!Doctype html>
<html>
    <head><title><%= yield(:title) %></title></head>
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-sm-12 col-xs-12 table-responsive col-md-offset-3">
                    <h2 class="text-center">Report</h2>
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <td class="table-dark">Infected Survivors</td>
                            <td>
                                <%= @infected_count %>
                            </td>
                        </tr>
                        <tr>
                            <td class="table-dark">Non-Infected Survivors</td>
                            <td><%= @non_infected_count %></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/survivals/show.html.erb
<% provide(:title, "My Profile") %>
<!Doctype html>
<html>
    <head><title><%= yield(:title) %></title></head>
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-sm-12 col-xs-12 table-responsive col-md-offset-3">
                    <h2 class="text-center">My Profile</h2>
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <td class="table-dark">Profile Picture</td>
                            <td>
                                <% if @survival.avatar.attached? %>
                                    <div><image src="<%= (url_for(@survival.avatar)) %>" class="survival-avatar"></div>
                                <% else %>
                                    <p>No image found</p>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <td class="table-dark">Name</td>
                            <td><%= current_user.name %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">Age</td>
                            <td><%= current_user.age %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">Gender</td>
                            <td><%= current_user.gender %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">Infected?</td>
                            <td><%= current_user.isInfectedCount && current_user.isInfectedCount >= 5 ? 'You are infected' : 'You are not infected' %></td>
                        </tr>
                        <tr>
                            <td class="table-dark">Marked Infected</td>
                            <td>
                                <% if current_user.isInfectedCount %>
                                You are marked infected by <%= current_user.isInfectedCount %> survivals
                                <% else %>
                                You are not marked infected by any survival
                                <% end %>
                            </td>
                        </tr>
                        <% if current_user.isInfectedCount != nil && current_user.isInfectedCount >= 5 %>
                            <tr><td colspan="2" class="bg-danger text-center infected_text">You are Infected by Virus</td></tr>
                        <% else %>
                        <tr>
                        <td colspan="2"><%= link_to 'Update Profile', edit_survival_path, class: "btn btn-warning" %></td>
                        <% end %>
                    </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>